name: Deploy Frozen Flask to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Freeze the Flask site
        run: |
          python app.py  # Assuming you have this script set up to run freezer.freeze()

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # This is where the frozen site will be generated
          # Ensure the token has the necessary permissions
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

